name: guestbook_dt
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  endec:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  endec_json:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  uuid: ^4.5.1
  mysql1: ^0.20.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
  endec_builder:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
